### ISSUE TITLE
I need help enabling the worldmodels on non bot clients.

### ISSUE THREAD

**Issue by Sharkmaw** [Zabaniya001/TF2CA-weaponmodel_override#1]
Sent you a DM on Alliedmods.net since you said it can't be shared publicly.

**Comment by TF2CutContentWiki** [comment]
It can be shared publicly, it's on the bloody forums and my Github.

Look up TF2 Serverside Player Attachment Fixer.

**Comment by tsuza** [comment]
Yeah, I'm aware. I had always been told that it was something that shouldn't be mentioned or posted until Asherkin cleared it up once and for all on Discord a month or two ago.  I'll change it and add it back. Thanks for reminding me.
