### ISSUE TITLE
Custom arm animations not visible

### ISSUE THREAD

**Issue by ShakerSaba** [Zabaniya001/TF2CA-weaponmodel_override#11]
I am looking to modify the viewmodel arms with a custom set of animations from a mod but they don't appear visible. I can however hear the sounds emitted by it so it appears to be loading but just not visible.
> TF2Attrib_SetFromStringValue(weapon,"set viewmodel arms","models/custom/c_sniper_arms.mdl");

Changing this attribute to set of arms in the base game appears to work as expected, so I presume there's something wrong with custom model itself. I might be missing something but the mod only comes with that model file, no additional materials, etc.

**Comment by tsuza** [comment]
Mhh, hard to work with that little information. I've tested it with a few custom arms and they worked just fine. 

I've attached the files to the claws weapon that are shown in the video. Try it out and let me know.

```
"set weapon model"         "models/weapons/custommodels/wolverine/c_machete.mdl"
"set viewmodel arms"    "models/weapons/custommodels/wolverine/c_sniper_arms.mdl"
```
[claws (2).zip](https://github.com/Zabaniya001/TF2CA-weaponmodel_override/files/11413569/claws.2.zip)

**Comment by ShakerSaba** [comment]
those files appeared to work. looked into it and comparing the files, it appears the mod I was using was simply incomplete, thanks.

**Comment by tsuza** [comment]
Glad you figured it out. Looks like this was resolved so I'll be closing it. If you have any other questions or issues feel free to open a new issue ( or if it's related to this just re-open this one ).
