### ISSUE TITLE
Cannot load plugin

### ISSUE THREAD

**Issue by zryuek** [Zabaniya001/TF2CA-weaponmodel_override#17]
SM Version: 1.11.0.6968
Dump:
> [SM] Exception reported: Invalid TF2EconDynAttribute handle 0 (error: 4)
> [SM] Blaming: attribute_viewmodel_override.smx
> [SM] Call stack trace:
> [SM]   [0] TF2EconDynAttribute.SetDescriptionFormat
> [SM]   [1] Line 124, C:\TFS\tf2server\tf\addons\sourcemod\scripting\attribute_viewmodel_override.sp::RegisterAttributes
> [SM]   [2] Line 71, C:\TFS\tf2server\tf\addons\sourcemod\scripting\attribute_viewmodel_override.sp::OnPluginStart

**Comment by tsuza** [comment]
That's not an issue with this plugin. It's an issue with https://github.com/nosoop/SMExt-TFEconDynamic, which is used to register the attribute. Make sure that it's updated, including the gamedata.

**Comment by zryuek** [comment]
My bad, I missed some dynamic econ files. Plugin loads now with no errors, but it doesn't seem to have any effect. I have ran the attribute through ff2r and cwx, but neither had any effect. Other custom attributes work just fine; Including nosoop's viewmodel override.

**Comment by tsuza** [comment]
Nosoop's viewmodel override uses a different method and it does not have animation support either. Keep in mind that for some odd reason it does not work properly on FF2R. Though it works everywhere else. One day I'll look again into it and figure out what FF2R does that causes the issue.

**Comment by zryuek** [comment]
I see, thanks for the clarification.
