### ISSUE TITLE
Broken as of latest TF2 update

### ISSUE THREAD

**Issue by sticks-stuff** [Zabaniya001/TF2CA-weaponmodel_override#3]
Weapons are invisible

**Comment by sticks-stuff** [comment]
I'm stupid, forgot to update gamedata

**Comment by sticks-stuff** [comment]
I'm stupid part 2: updating gamedata didn't actually fix it
![image](https://user-images.githubusercontent.com/4157860/123506143-d4f2b580-d6b6-11eb-836d-7d4ad71e647e.png)

**Comment by jack5github** [comment]
Confirmed that overriding models are completely invisible.

**Comment by tsuza** [comment]
Sorry guys, didn't see this issue. I've updated the gamedata.
