### ISSUE TITLE
Demo shield model doesn't loading

### ISSUE THREAD

**Issue by CDTH06** [Zabaniya001/TF2CA-weaponmodel_override#5]
When I use this attribute on demo shield, model doesn't loads

**Comment by tsuza** [comment]
Shields are not supported as of now since they work differently. The code to support them is sitting somewhere in storage, I just need to finish it

**Comment by CDTH06** [comment]
Ok. And I have question: Did you gonna try to make same attributes for building models ,wearables (shield, backpack for bunners and medi guns etc.) and animations models? Just curious

**Comment by tsuza** [comment]
This attribute will be updated so it supports weapon wearables ( so shields, backpacks etc... ) eventually.

Building models might be an idea for a future attribute. The server I develop for already has it, but it's private. 

What do you mean by "animations models"? Taunts? If so, there is an [existing one](https://github.com/Batfoxkid/TF2-Custom-Taunts).

**Comment by CDTH06** [comment]
About animation models, I mean 1st person animations for weapons. Like dead finger from Karma videos.

**Comment by tsuza** [comment]
Unfortunately that's something that can't be done via plugins. Karma is able to have those animations because he manually replaced the model with a custom one.

**Comment by tsuza** [comment]
Now you can have custom 1st person animations. #10
